import "../globals.css";
import "tw-elements/dist/css/tw-elements.min.css";
import type { Metadata } from "next";
import { Inter, Roboto, Libre_Caslon_Display } from "next/font/google";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import { roboto } from "@/fonts";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
